%Script for plotting logfiles generated by Testing_USCities_N.m 

%first load a logfile and then run this script to plot the contents

DCATime        = [LogsDCA.time];
BDCATime       = [LogsBDCA.time];
BDCA_AdaptTime = [LogsBDCA_adapt.time];

DCAIter        = [LogsDCA.totaliter];
BDCAIter       = [LogsBDCA.totaliter];
BDCA_AdaptIter = [LogsBDCA_adapt.totaliter];

N = length(DCAIter);

figure()
plot(DCATime./BDCATime,'rx','MarkerFaceColor','r','MarkerSize',8)
hold on
p1 = plot(ones(1,N)*mean(DCATime./BDCATime),'b-.');
hold off
xlabel('Run')
ylabel('Time Ratio')
title('DCA/BDCA')
fontsize(15,'points');
legend(p1,{'Average Time Ratio'});

figure()
plot(DCATime./BDCA_AdaptTime,'kx','MarkerFaceColor','r','MarkerSize',8)
hold on
p2 = plot(ones(1,N)*mean(DCATime./BDCA_AdaptTime),'b-.');
hold off
xlabel('Run')
ylabel('Time Ratio')
title('DCA/BDCA adaptive')
fontsize(15,'points');
legend(p2,{'Average Time Ratio'});


figure()
plot(DCAIter./BDCAIter,'rx','MarkerFaceColor','r','MarkerSize',8)
hold on
p3 = plot(ones(1,N)*mean(DCAIter./BDCAIter),'b-.');
hold off
xlabel('Run')
ylabel('Iteration Ratio')
title('DCA/BDCA')
fontsize(15,'points');
legend(p3,{'Average Iteration Ratio'});


figure()
plot(DCAIter./BDCA_AdaptIter,'kx','MarkerFaceColor','r','MarkerSize',8)
hold on
p4 = plot(ones(1,N)*mean(DCAIter./BDCA_AdaptIter),'b-.');
hold off
xlabel('Run')
ylabel('Iteration Ratio')
title('DCA/BDCA adaptive')
fontsize(15,'points');
legend(p4,{'Average Iteration Ratio'});
